ngo/config/routes.rb
Rails.application.routes.draw do
  get 'data/display'
  resources :country_data_finals
  root 'country_data_finals#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

ngo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ngo/app/models/country_data_final.rb
class CountryDataFinal < ApplicationRecord
end

ngo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ngo/app/controllers/country_data_finals_controller.rb
class CountryDataFinalsController < ApplicationController
  before_action :set_country_data_final, only: %i[ show edit update destroy ]

  # GET /country_data_finals or /country_data_finals.json
  def index
    @country_data_finals = CountryDataFinal.all
  end

  # GET /country_data_finals/1 or /country_data_finals/1.json
  def show
  end

  # GET /country_data_finals/new
  def new
    @country_data_final = CountryDataFinal.new
  end

  # GET /country_data_finals/1/edit
  def edit
  end

  # POST /country_data_finals or /country_data_finals.json
  def create
    @country_data_final = CountryDataFinal.new(country_data_final_params)

    respond_to do |format|
      if @country_data_final.save
        format.html { redirect_to country_data_final_url(@country_data_final), notice: "Country data final was successfully created." }
        format.json { render :show, status: :created, location: @country_data_final }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country_data_final.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /country_data_finals/1 or /country_data_finals/1.json
  def update
    respond_to do |format|
      if @country_data_final.update(country_data_final_params)
        format.html { redirect_to country_data_final_url(@country_data_final), notice: "Country data final was successfully updated." }
        format.json { render :show, status: :ok, location: @country_data_final }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country_data_final.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /country_data_finals/1 or /country_data_finals/1.json
  def destroy
    @country_data_final.destroy!

    respond_to do |format|
      format.html { redirect_to country_data_finals_url, notice: "Country data final was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country_data_final
      @country_data_final = CountryDataFinal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_data_final_params
      params.require(:country_data_final).permit(:name, :mobilephones, :mortalityunder5, :healthexpenditurepercapita, :healthexpenditureppercentgdp, :population, :populationurban, :birthrate, :lifeexpectancy, :gdp)
    end
end

ngo/app/controllers/data_controller.rb
class DataController < ApplicationController
  def display
    @country_data = CountryDataFinal.all
  end
end

ngo/app/helpers/application_helper.rb
module ApplicationHelper
end

ngo/app/helpers/country_data_finals_helper.rb
module CountryDataFinalsHelper
end

ngo/app/helpers/data_helper.rb
module DataHelper
end

ngo/app/views/country_data_finals/_country_data_final.html.erb
<div id="<%= dom_id country_data_final %>">
  <p>
    <strong>Name:</strong>
    <%= country_data_final.name %>
  </p>

  <p>
    <strong>Mobilephones:</strong>
    <%= country_data_final.mobilephones %>
  </p>

  <p>
    <strong>Mortalityunder5:</strong>
    <%= country_data_final.mortalityunder5 %>
  </p>

  <p>
    <strong>Healthexpenditurepercapita:</strong>
    <%= country_data_final.healthexpenditurepercapita %>
  </p>

  <p>
    <strong>Healthexpenditureppercentgdp:</strong>
    <%= country_data_final.healthexpenditureppercentgdp %>
  </p>

  <p>
    <strong>Population:</strong>
    <%= country_data_final.population %>
  </p>

  <p>
    <strong>Populationurban:</strong>
    <%= country_data_final.populationurban %>
  </p>

  <p>
    <strong>Birthrate:</strong>
    <%= country_data_final.birthrate %>
  </p>

  <p>
    <strong>Lifeexpectancy:</strong>
    <%= country_data_final.lifeexpectancy %>
  </p>

  <p>
    <strong>Gdp:</strong>
    <%= country_data_final.gdp %>
  </p>

</div>

ngo/app/views/country_data_finals/_form.html.erb
<%= form_with(model: country_data_final) do |form| %>
  <% if country_data_final.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country_data_final.errors.count, "error") %> prohibited this country_data_final from being saved:</h2>

      <ul>
        <% country_data_final.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :mobilephones, style: "display: block" %>
    <%= form.text_field :mobilephones %>
  </div>

  <div>
    <%= form.label :mortalityunder5, style: "display: block" %>
    <%= form.text_field :mortalityunder5 %>
  </div>

  <div>
    <%= form.label :healthexpenditurepercapita, style: "display: block" %>
    <%= form.text_field :healthexpenditurepercapita %>
  </div>

  <div>
    <%= form.label :healthexpenditureppercentgdp, style: "display: block" %>
    <%= form.text_field :healthexpenditureppercentgdp %>
  </div>

  <div>
    <%= form.label :population, style: "display: block" %>
    <%= form.text_field :population %>
  </div>

  <div>
    <%= form.label :populationurban, style: "display: block" %>
    <%= form.text_field :populationurban %>
  </div>

  <div>
    <%= form.label :birthrate, style: "display: block" %>
    <%= form.text_field :birthrate %>
  </div>

  <div>
    <%= form.label :lifeexpectancy, style: "display: block" %>
    <%= form.text_field :lifeexpectancy %>
  </div>

  <div>
    <%= form.label :gdp, style: "display: block" %>
    <%= form.text_field :gdp %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

ngo/app/views/country_data_finals/edit.html.erb
<h1>Editing country data final</h1>

<%= render "form", country_data_final: @country_data_final %>

<br>

<div>
  <%= link_to "Show this country data final", @country_data_final %> |
  <%= link_to "Back to country data finals", country_data_finals_path %>
</div>

ngo/app/views/country_data_finals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Country data finals</h1>

<div id="country_data_finals">
  <% @country_data_finals.each do |country_data_final| %>
    <%= render country_data_final %>
    <p>
      <%= link_to "Show this country data final", country_data_final %>
    </p>
  <% end %>
</div>

<%= link_to "New country data final", new_country_data_final_path %>

ngo/app/views/country_data_finals/new.html.erb
<h1>New country data final</h1>

<%= render "form", country_data_final: @country_data_final %>

<br>

<div>
  <%= link_to "Back to country data finals", country_data_finals_path %>
</div>

ngo/app/views/country_data_finals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country_data_final %>

<div>
  <%= link_to "Edit this country data final", edit_country_data_final_path(@country_data_final) %> |
  <%= link_to "Back to country data finals", country_data_finals_path %>

  <%= button_to "Destroy this country data final", @country_data_final, method: :delete %>
</div>

ngo/app/views/data/display.html.erb
<div class="w3-container">
  <h2>Country Data</h2>

  <% @country_data.each do |data| %>
    <div class="w3-card-4">
      <div class="w3-container">
        <h3><%= data.name %></h3>
        <p>Mobile Phones: <%= data.mobilephones %></p>
        <p>Mortality Under 5: <%= data.mortalityunder5 %></p>
        <p>health Expenditure Per Capita: <%= data.healthexpenditurepercapita %> </p>
        <p>health expenditure percent gdp: <%= data.healthexpenditureppercentgdp %></p>
        <p>population: <%= data.population %></p>
        <p>population urban: <%= data.populationurban %></p>
        <p>birthrate: <%= data.birthrate %></p>
        <p>life expectancy: <%= data.lifeexpectancy %></p>
        <p>gdp: <%= data.gdp %></p>
        <!-- Add more fields as needed -->
      </div>
    </div>
  <% end %>
</div>

ngo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ngo</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <div class="w3-container w3-teal">
  <h2>My NGO Website</h2>
</div>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <body style="background-color:#AEC6CF">
    <%= yield %>
  </body>
</html>